### ISSUE TITLE
Update to RC4

### ISSUE THREAD

**Issue by ghost** [bartsqueezy/ember-handlebars-brunch#4] opened 2013-05-30 13:05 UTC
Both Ember and Handlebars are now at RC4. Could we get an update for this? I've tried most of the morning to get it to work, but have had no success until now. I'm happy to make it happen if somebody could lend a hand.

**Comment by bartsqueezy** [comment] 2013-06-03 04:34
Thanks for the friendly reminder!  I will work on this tomorrow.

**Comment by bartsqueezy** [comment] 2013-06-06 19:38
After testing to ensure that an upgrade to ember rc-5 would not break this plugin, I discovered that there is a bug within ember.js that prevents using the ember-template-compiler dist with the latest handlebars.js 1.0.0.  It does, however, work with 1.0.0-rc.4.  Until I can debug what the problem is here, I'm just going to upgrade ember to rc-5 and leave handlebars.js at rc-4.  Once a fix is in place, I'll upgrade handlebars to the latest release.

Thanks again!

**Closed as completed** 2013-06-06 19:39 UTC
Labels: update libs
